import * as THREE from 'three/webgpu';

// === Immutable Config Constants ===

const BASE_SCALE = 0.52;
const HOVER_SCALE = 0.72;
const FOV_RAD = THREE.MathUtils.degToRad(50);
const MIN_ZOOM = 0.1;
const TOP_ZONE_RATIO = 0.15;
const BOTTOM_ZONE_RATIO = 0.15;
const DRAG_THRESHOLD = 3;
const INERTIA_DECAY = 0.975;
const INERTIA_FAST_DECAY = 0.85;
const INERTIA_MIN = 0.0005;
const SPEED_SAMPLES = 5;
const LONG_PRESS_MS = 600;

export { BASE_SCALE, HOVER_SCALE, FOV_RAD, MIN_ZOOM, TOP_ZONE_RATIO, BOTTOM_ZONE_RATIO, DRAG_THRESHOLD, INERTIA_DECAY, INERTIA_FAST_DECAY, INERTIA_MIN, SPEED_SAMPLES, LONG_PRESS_MS };
